-- V10: Data quality log table for tracking data issues and anomalies
-- Logs data quality issues per ticker with issue type and details
-- References: supabase_v8_phase1_migration.sql style (Korean comments, idempotent)

create table if not exists data_quality_log (
  id bigint generated by default as identity primary key,
  ticker text not null,
  issue_type text not null,
  details jsonb,
  logged_at timestamptz not null default now()
);

-- 인덱스: 티커별 품질 이슈 조회 및 시간 기반 검색
create index if not exists idx_data_quality_ticker_logged_at
  on data_quality_log(ticker, logged_at);