-- V8 Phase 6: 역사적 classification/펀더멘털 스냅샷 테이블
-- 백테스트 시점의 classification 및 fundamental 데이터를 캐시하여
-- 장기 백테스트에서Classification 변경을 보정한다.

-- Historical classification snapshots
-- 한 종목의 특정 시점(strategy_type, confidence) 스냅샷을 보존한다.
-- DB에 저장된 classify_asset 결과나, 이전 스캔 결과 등을 재사용할 수 있다.
CREATE TABLE IF NOT EXISTS historical_classification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    effective_date date NOT NULL,
    strategy_type text NOT NULL,
    confidence float,
    source text,  -- 'db_lookup' | 'classify_asset' | 'manual'
    created_at timestamptz DEFAULT now(),
    UNIQUE(ticker, effective_date)
);

-- Historical fundamental data snapshots
-- 특정 시점의 fundamental 데이터(JSONB)를 보존한다.
-- Yahoo Finance 데이터가 변동되더라도 백테스트 재현성을 위해 보존한다.
CREATE TABLE IF NOT EXISTS historical_fundamental (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    period_end date NOT NULL,
    available_date date NOT NULL,
    data jsonb NOT NULL,
    created_at timestamptz DEFAULT now(),
    UNIQUE(ticker, period_end)
);