-- V10: Scan runs table for tracking scan execution history
-- Creates a log of scan runs with counts and status tracking
-- References: supabase_v8_phase1_migration.sql style (Korean comments, idempotent)

create table if not exists scan_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  watchlist_count integer not null default 0,
  evaluated_count integer not null default 0,
  signal_count integer not null default 0,
  failure_count integer not null default 0,
  status text not null default 'running',
  version text not null default 'v10',
  error_summary text
);

-- 인덱스: 시간순 조회 및 타임스탬프 기반 검색
create index if not exists idx_scan_runs_started_at
  on scan_runs(started_at);