create table if not exists daily_data (
  date date not null,
  ticker text not null,
  price double precision,
  rsi double precision,
  prev_rsi double precision,
  ma20 double precision,
  ma50 double precision,
  drawdown double precision,
  volume_ratio double precision,
  score integer,
  primary key (date, ticker)
);

create table if not exists signals (
  id bigint generated by default as identity primary key,
  signal_date date not null,
  ticker text not null,
  signal_price double precision,
  score integer,
  rsi double precision,
  drawdown double precision,
  return_5d double precision,
  return_10d double precision,
  return_20d double precision,
  unique(signal_date, ticker)
);

create table if not exists watchlist (
  ticker text primary key,
  name text not null,
  active boolean not null default true
);

create index if not exists idx_daily_ticker_date
  on daily_data(ticker, date);

create index if not exists idx_signals_date
  on signals(signal_date);

create index if not exists idx_signals_ticker
  on signals(ticker);
